# Generated by Django 4.2.4 on 2023-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_skill_remove_user_skills_user_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalqualification',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='educationalqualification',
            name='skills',
            field=models.ManyToManyField(blank=True, to='account.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_pictures'),
            preserve_default=False,
        ),
    ]
