# Generated by Django 4.2.4 on 2023-09-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comment_name_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='previous_projects/')),
                ('link', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='achievement',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.previousproject'),
            preserve_default=False,
        ),
    ]
