# Generated by Django 4.2.4 on 2023-09-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_previousproject_remove_comment_achievement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='PreviousProject',
        ),
    ]
